{
"openapi": "3.0.1",
"info": {
"title": "API Factory - Object Stream API",
"description": "Object Stream API",
"termsOfService": "http://datahub.mksmart.org",
"contact": {
"email": "datahub-support@mksmart.org"
},
"license": {
"name": "Apache 2.0",
"url": "http://www.apache.org/licenses/LICENSE-2.0.html"
},
"version": "0.6.0"
},
"tags": [
{
"name": "query",
"description": "Query documents (included for backwards compatibility - please use Object or Browse)",
"externalDocs": {
"description": "Find out more",
"url": "https://datahub.mksmart.org"
}
},
{
"name": "browse",
"description": "Browse a dataset, with full control over filters, pagination, sorting"
},
{
"name": "object",
"description": "retrieve, push, update and delete documents"
}
],
"paths": {
"/query/{dataset-uuid}": {
"post": {
"tags": [
"query"
],
"summary": "Query a dataset",
"description": "Pass a MongoDB query in the body of this request to query the dataset, or pass an empty body to return all documents",
"operationId": "query",
"parameters": [
{
"name": "dataset-uuid",
"in": "path",
"required": true,
"schema": {
"type": "string"
}
},
{
"name": "limit",
"in": "query",
"description": "Optionally limit the number of documents returned",
"schema": {
"minimum": 0,
"type": "integer"
}
}
],
"requestBody": {
"description": "The filter query",
"content": {
"application/json": {
"schema": {
"type": "object",
"example": {
"sensorID": "42-a"
}
}
}
},
"required": false
},
"responses": {
"200": {
"description": "Success",
"content": {
"application/json": {
"schema": {
"type": "object",
"example": {
"_id": "1067",
"sensorID": "42-a",
"sensorValue": 34.7
}
}
}
}
},
"400": {
"description": "Bad request, dataset uuid not specified",
"content": {}
},
"401": {
"description": "Unauthorized. Dataset key must be provided as HTTP Basic Auth username",
"content": {}
},
"404": {
"description": "Object not found",
"content": {}
},
"405": {
"description": "Method not allowed",
"content": {}
}
}
}
},
"/browse/{dataset-uuid}": {
"get": {
"tags": [
"browse"
],
"summary": "Retrieve documents from the dataset",
"operationId": "getDocuments",
"parameters": [
{
"name": "dataset-uuid",
"in": "path",
"description": "dataset uuid identifier",
"required": true,
"schema": {
"type": "string"
}
},
{
"name": "query",
"in": "query",
"description": "The filter query",
"required": false,
"schema": {
"type": "string"
}
},
{
"name": "limit",
"in": "query",
"description": "Optionally limit the number of documents returned",
"schema": {
"minimum": 0,
"type": "integer"
}
},
{
"name": "sort",
"in": "query",
"description": "Optionally specify fields on which to sort the data. Sort fields should be specified as a comma seperated list. Data will be sorted in ascending order. To specify a field to sort in descending order precede that field with a minus ('-')",
"schema": {
"type": "string"
}
},
{
"name": "pagesize",
"in": "query",
"description": "Optionally enable pagination and specify page size",
"schema": {
"minimum": 0,
"type": "integer"
}
},
{
"name": "page",
"in": "query",
"description": "If using pagination, optionally specify the page number of results to return (defaults to page 1)",
"schema": {
"minimum": 0,
"type": "integer"
}
}
],
"responses": {
"200": {
"description": "Success"
},
"400": {
"description": "Bad request, malformed JSON"
},
"500": {
"description": "Fatal error creating object"
}
}
}
},
"/object/{dataset-uuid}": {
"get": {
"tags": [
"object"
],
"summary": "Retrieve documents from the dataset",
"operationId": "getDocuments",
"parameters": [
{
"name": "dataset-uuid",
"in": "path",
"description": "dataset uuid identifier",
"required": true,
"schema": {
"type": "string"
}
},
{
"name": "query",
"in": "query",
"description": "The filter query",
"required": false,
"schema": {
"type": "string"
}
},
{
"name": "limit",
"in": "query",
"description": "Optionally limit the number of documents returned",
"schema": {
"minimum": 0,
"type": "integer"
}
}
],
"responses": {
"200": {
"description": "Success"
},
"400": {
"description": "Bad request, malformed JSON"
},
"500": {
"description": "Fatal error creating object"
}
}
},
"post": {
"tags": [
"object"
],
"summary": "Create a new document in the dataset",
"operationId": "createDocument",
"parameters": [
{
"name": "dataset-uuid",
"in": "path",
"description": "dataset uuid identifier",
"required": true,
"schema": {
"type": "string"
}
}
],
"requestBody": {
"description": "The document to be created",
"content": {
"application/json": {
"schema": {
"type": "object",
"example": {
"_id": "1067",
"sensorID": "42-a",
"sensorValue": 34.7
}
}
}
},
"required": true
},
"responses": {
"201": {
"description": "Object created"
},
"400": {
"description": "Bad request, malformed JSON"
},
"500": {
"description": "Fatal error creating object"
}
}
}
},
"/object/{dataset-uuid}/{doc_id}": {
"get": {
"tags": [
"object"
],
"summary": "Retrieve a single document from the dataset",
"operationId": "getDocument",
"parameters": [
{
"name": "dataset-uuid",
"in": "path",
"description": "dataset uuid identifier",
"required": true,
"schema": {
"type": "string"
}
},
{
"name": "doc_id",
"in": "path",
"required": true,
"schema": {
"type": "string"
}
},
{
"name": "limit",
"in": "query",
"description": "Optionally limit the number of documents returned",
"schema": {
"minimum": 0,
"type": "integer"
}
}
],
"responses": {
"200": {
"description": "Success"
},
"400": {
"description": "Bad request, malformed JSON"
},
"500": {
"description": "Fatal error creating object"
}
}
},
"put": {
"tags": [
"object"
],
"summary": "Update a document by ID",
"description": "Update an existing document, referenced by ID. Note that the existing document will be overwritten, so a full document should be supplied.",
"operationId": "updateDocumentById",
"parameters": [
{
"name": "dataset-uuid",
"in": "path",
"description": "The UUID of the dataset",
"required": true,
"schema": {
"type": "string"
}
},
{
"name": "doc_id",
"in": "path",
"required": true,
"schema": {
"type": "string"
}
}
],
"requestBody": {
"description": "The updated document",
"content": {
"application/json": {
"schema": {
"type": "object"
}
}
},
"required": true
},
"responses": {
"201": {
"description": "Object creted"
},
"204": {
"description": "Object updated"
},
"500": {
"description": "Fatal error creating or updating object"
}
}
},
"delete": {
"tags": [
"object"
],
"summary": "Delete a document by ID",
"description": "Delete an existing document, referenced by ID.",
"operationId": "deleteDocumentById",
"parameters": [
{
"name": "dataset-uuid",
"in": "path",
"description": "The UUID of the dataset",
"required": true,
"schema": {
"type": "string"
}
},
{
"name": "doc_id",
"in": "path",
"required": true,
"schema": {
"type": "string"
}
}
],
"responses": {
"200": {
"description": "No items to delete"
},
"204": {
"description": "Object deleted"
},
"500": {
"description": "Fatal error deleting object"
}
}
}
}
},
"externalDocs": {
"description": "Find out more about the API Factory",
"url": "http://datahu.mksmart.org"
},
"servers": [
{
"url": "<?= $this->basePath() ?>"
}
],
"security": [
{
"DatasetAuth": []
}
],
"components": {
"securitySchemes": {
"DatasetAuth": {
"type": "http",
"scheme": "basic"
}
}
}
}